#!/bin/bash

#  Menu for ExpressVPN with Tray Icon v1.1  github.com/powerhousepro69/xvpn

#     Requirements:  - Expressvpn CLI App  <expressvpn>
#                    - Included python script   [vpn_notificaton.py]   

#       **********   Put  vpn_notificaton.py  in   ~/.config   **********

#  Note : you can shutdown expressvpn from the tray icon.


#     Put  xvpn  file wherever you want.
#     To enable execute bit:

#    - Open Terminal
#    - Switch to the directory that  xvpn  is in.
#    - Enable execute bit type..    chmod +x xvpn 

# If this file isn't in the path and you are in the directory it is in   ./xvpn   to run 
# If the file is located in your path:      enter...       xvpn    to run

provider_cli=expressvpn

function status {
	clear
	echo ""
	echo ""
	$provider_cli status
        echo -en "\n\n\t\t\tHit any key to continue"
	read -n 1 line
}

function lastconnect {
	clear
    	echo ""
	echo ""
	$provider_cli connect
}

function smart {
	clear
	echo ""
	echo ""
	$provider_cli connect smart
}

function disconnect {
	clear
	echo ""
	echo ""
	$provider_cli disconnect
	notify-send 'VPN Tray Icon - SHUTDOWN'
}

function pref {
        clear
        echo ""
	echo ""        
	$provider_cli preferences
	echo -en "\n\n\t\t\tHit any key to continue"
	read -n 1 line
}

function nlockon {
        clear
        echo ""
	echo "" 
	$provider_cli preferences set network_lock on
	echo -en "\n\n\t\t\tHit any key to continue"
	read -n 1 line
}

function las {
        clear
        echo ""
	echo "" 
	$provider_cli list all
	echo "" 
	echo ""
	echo "  Scroll up with mouse to find what server you want. (server code on far left)"
	echo "  Scroll back down and enter server code."
	echo "  " 
	echo "  If you do not enter anything, your last connection will be used. "
	echo "" 
	read -p "  Enter Sever Code and Press ENTER :  " svrcode 
        $provider_cli connect $svrcode
        read -p "  Press  ENTER to continue . . ." 
}

function vernum {
        clear
        echo ""
	echo "" 
	$provider_cli -v
	echo -en "\n\n\t\t\tHit any key to continue"
	read -n 1 line
}

function nlockoff {
        clear
        echo ""
	echo "" 
	$provider_cli preferences set network_lock off 
	echo -en "\n\n\t\t\tHit any key to continue"
	read -n 1 line
}

function enteract {
        clear
        echo ""
	echo "" 
	echo "  Enter or Paste your Activation Code Below"
	echo "  Then Press ENTER"
        echo "" 
	echo ""
    # read -p "   Activation Code:  " ac 
        $provider_cli activate $ac 
}

function dallas {
	clear
	echo ""
	echo ""	
        $provider_cli connect usda 
}


function la {
	clear
	echo ""
	echo ""	
	$provider_cli connect usla
}

function la2 {
	clear
	echo ""
	echo ""	
	$provider_cli connect usla2
}

function ny {
	clear
	echo ""
	echo ""	
	$provider_cli connect usny
}


function sanfran {
	clear
	echo ""
	echo ""	
	$provider_cli connect ussf
}

function seattle {
	clear
	echo ""
	echo ""	
	$provider_cli connect usse 
}


function dc {
	clear
	echo ""
	echo ""	
	$provider_cli connect uswd 
}


function amsterdam {
	clear
	echo ""
	echo ""
	$provider_cli connect nlam
}

function belgium {
	clear
	echo ""
	echo ""
	$provider_cli connect be
}

function elondon {
	clear
	echo ""
	echo ""
	$provider_cli connect ukel
}

function frankfurt {
	clear
	echo ""
	echo ""
	$provider_cli connect defr1
}

function hkong2 {
	clear
	echo ""
	echo ""
	$provider_cli connect hk2
}

function milan {
	clear
	echo ""
	echo ""
	$provider_cli connect itmi
}

function paris1 {
	clear
	echo ""
	echo ""
	$provider_cli connect frpa1
}

function switzerland2 {
	clear
	echo ""
	echo ""
	$provider_cli connect ch2
}

function toronto {
	clear
	echo ""
	echo ""
	$provider_cli connect cato
}

function menu {
clear
echo ""
echo "           Menu for ExpressVPN with Tray Icon       "
echo "     ______________________________________________ "
echo "    |                     |                        |"
echo "    | 1. Status           | 6. Enable Net Lock     |"
echo "    | 2. Connect to Last  | 7. List All Servers    |"    
echo "    | 3. Smart Connect    | 8. Version Number      |"
echo "    | 4. Disconnect       | !. Disable Net Lock    |"
echo "    | 5. Preferences      | $. Enter Activation    |"
echo "    |---------------------|------------------------|"
echo "    |         USA         |         OTHER          |"
echo "    |---------------------|------------------------|"	
echo "    | a. Dallas           | h. Amsterdam - NL      |"
echo "    | b. Los Angeles      | i. Belgium             |"
echo "    | c. Los Angeles 2    | j. East London - UK    |"
echo "    | d. New York         | k. Frankfurt - Germany |"
echo "    | e. San Francisco    | l. Hong Kong 2         |"
echo "    | f. Seattle          | m. Milan - Italy       |"	
echo "    | g. Washington DC    | n. Paris 1 - France    |"
echo "    |---------------------| o. Switzerland 2       |"
echo "    |       0. EXIT       | p. Toronto - Canada    |"
echo "    |_____________________|________________________|"


#######################################################################################
if ifconfig tun0 | grep -q "00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00"
then
	if pgrep -af 'python3 /home/'$USER'/.config/vpn_notification.py' >/dev/null
        then
    		echo "        ExpressVPN and Tray Icon - ACTIVE"
	else
		nohup python3 ~/.config/vpn_notification.py &> /dev/null &
		notify-send 'VPN Tray Icon - LOADED'
		echo "        ExpressVPN and Tray Icon - LOADED"	
        fi
else
  	killall -q python3 ~/.config/vpn_notification.py
	echo "        ExpressVPN and Tray Icon - SHUTDOWN"
	fi
#######################################################################################
	
echo -en "\tEnter an Option: "
read -n 1 option
}


while [ 1 ]
do
	menu
	case $option in
	0)
	break ;;
	1)
	status ;;

	2)
	lastconnect ;;

	3)
	smart ;;

	4)
	disconnect ;;

	5)
	pref ;;

	6)
	nlockon ;;

	7)
	las ;;

	8)
	vernum ;;

	!)
	nlockoff ;;

	$)
	enteract ;;

	a)
	dallas ;;

	b)
	la ;;

	c)
	la2 ;;

	d)
	ny ;;

	e)
	sanfran ;;

	f)
	seattle ;;

	g)
	dc ;;

	h)
	amsterdam ;;

	i)
	belgium ;;

	j)
	elondon ;;

	k)
	frankfurt ;;

	l)
	hkong2 ;;

	m)
	milan ;;

	n)
	paris1 ;;

	o)
	switzerland2 ;;

	p)
	toronto ;;


	*)
	clear
	echo ""
	echo ""
	echo ""	
	echo "                        Invalid Selection";;
	esac

#  Uncomment the 2 lines below to see all expressvpn messages.

#       echo -en "\n\n\t\t\tHit any key to continue"
#       read -n 1 line
done
clear



