#!/bin/bash
#
#  Menu for ExpressVPN with Tray Icon v1.1
#
#     Requirements:  - ExpressVPN CLI App
#                    - Included python script   [vpn_notificaton.py]   
#
#     READ !!   **** - If you don't place  [vpn_notification.py]
#                      in  ~/bin/   you will need to edit 3 lines in this script.
#                      Instructions at  LINE 275
#
# 
#
# Put this file in a directory in the path and enable execute bit.
#
# To do this from the terminal:
#
#    - Open Terminal
#    - Switch to the directory that  xvpn  is in.
#    - Enable execute bit type..    chmod +x xvpn 
#
# If the execute bit isn't enabled, this bash script won't run.
#
#
# If this file isn't in the path and you are in the directory it is
# located in... enter...     ./xvpn    to run 
#
#
# If the file is located in your path:      enter...       xvpn    to run
#
#

function status {
	clear
	echo ""
	echo ""
	expressvpn status
        echo -en "\n\n\t\t\tHit any key to continue"
	read -n 1 line
}

function lastconnect {
	clear
    	echo ""
	echo ""
	expressvpn connect
}

function smart {
	clear
	echo ""
	echo ""
	expressvpn connect smart
}

function disconnect {
	clear
	echo ""
	echo ""
	expressvpn disconnect
	notify-send 'VPN Tray Icon - SHUTDOWN'
}

function pref {
        clear
        echo ""
	echo ""        
	expressvpn preferences
	echo -en "\n\n\t\t\tHit any key to continue"
	read -n 1 line
}

function nlockon {
        clear
        echo ""
	echo "" 
	expressvpn preferences set network_lock on
	echo -en "\n\n\t\t\tHit any key to continue"
	read -n 1 line
}

function las {
        clear
        echo ""
	echo "" 
	expressvpn list all
	echo "" 
	echo ""
	echo "  Scroll up with mouse to find what server you want."
	echo "  Then scoll back down to enter it."
	echo "  If you do not enter anything," 
	echo "  your last connection will be used."
	echo "" 
	echo ""
	read -p "  Enter Sever Code and Press ENTER :  " svrcode 
        expressvpn connect $svrcode
}

function vernum {
        clear
        echo ""
	echo "" 
	expressvpn -v
	echo -en "\n\n\t\t\tHit any key to continue"
	read -n 1 line
}

function nlockoff {
        clear
        echo ""
	echo "" 
	expressvpn preferences set network_lock off 
	echo -en "\n\n\t\t\tHit any key to continue"
	read -n 1 line
}

function enteract {
        clear
        echo ""
	echo "" 
	echo "  Enter or Paste your Activation Code Below"
	echo "  Then Press ENTER"
        echo "" 
	echo ""
    # read -p "   Activation Code:  " ac 
        expressvpn activate $ac 
}

function dallas {
	clear
	echo ""
	echo ""	
        expressvpn connect usda 
}


function la {
	clear
	echo ""
	echo ""	
	expressvpn connect usla
}

function la2 {
	clear
	echo ""
	echo ""	
	expressvpn connect usla2
}

function ny {
	clear
	echo ""
	echo ""	
	expressvpn connect usny
}


function sanfran {
	clear
	echo ""
	echo ""	
	expressvpn connect ussf
}

function seattle {
	clear
	echo ""
	echo ""	
	expressvpn connect usse 
}


function dc {
	clear
	echo ""
	echo ""	
	expressvpn connect uswd 
}


function amsterdam {
	clear
	echo ""
	echo ""
	expressvpn connect nlam
}

function belgium {
	clear
	echo ""
	echo ""
	expressvpn connect be
}

function elondon {
	clear
	echo ""
	echo ""
	expressvpn connect ukel
}

function frankfurt {
	clear
	echo ""
	echo ""
	expressvpn connect defr1
}

function hkong2 {
	clear
	echo ""
	echo ""
	expressvpn connect hk2
}

function milan {
	clear
	echo ""
	echo ""
	expressvpn connect itmi
}

function paris1 {
	clear
	echo ""
	echo ""
	expressvpn connect frpa1
}

function switzerland2 {
	clear
	echo ""
	echo ""
	expressvpn connect ch2
}

function toronto {
	clear
	echo ""
	echo ""
	expressvpn connect cato
}

function menu {
clear
echo ""
echo "           Menu for ExpressVPN with Tray Icon       "
echo "     ______________________________________________ "
echo "    |                     |                        |"
echo "    | 1. Status           | 6. Enable Net Lock     |"
echo "    | 2. Connect to Last  | 7. List All Servers    |"    
echo "    | 3. Smart Connect    | 8. Version Number      |"
echo "    | 4. Disconnect       | !. Disable Net Lock    |"
echo "    | 5. Preferences      | $. Enter Activation    |"
echo "    |---------------------|------------------------|"
echo "    |         USA         |         OTHER          |"
echo "    |---------------------|------------------------|"	
echo "    | a. Dallas           | h. Amsterdam - NL      |"
echo "    | b. Los Angeles      | i. Belgium             |"
echo "    | c. Los Angeles 2    | j. East London - UK    |"
echo "    | d. New York         | k. Frankfurt - Germany |"
echo "    | e. San Francisco    | l. Hong Kong 2         |"
echo "    | f. Seattle          | m. Milan - Italy       |"	
echo "    | g. Washington DC    | n. Paris 1 - France    |"
echo "    |---------------------| o. Switzerland 2       |"
echo "    |       0. EXIT       | p. Toronto - Canada    |"
echo "    |_____________________|________________________|"

#########################################################################
########## Code that checks if VPN Connection is Active.
########## If VPN is Active, it loads the tray icon if not aleady loaded.
########## When VPN gets disconnected the tray icon process is killed.
########## 
########## If you didn't put [vpn_noyification.py] in   ~/bin  
########## You need to change all 3 directories below to match the path
########## of where you have put   [vpn_notificaton.py]
##########
########## Note : you can shutdown expressvpn from the tray icon.
#######################################################################################
if ifconfig tun0 | grep -q "00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00"
then

	if pgrep -af 'python3 /home/'$USER'/bin/vpn_notification.py' >/dev/null; then
    		echo "        VPN Tray Icon - ACTIVE"
	else
		echo "        VPN Tray Icon - LOADED"
		nohup python3 ~/bin/vpn_notification.py &> /dev/null &
		notify-send 'VPN Tray Icon - LOADED'	
        fi
else
  	killall -q python3 ~/bin/vpn_notification.py
	echo "        Express VPN and Tray Icon - SHUTDOWN"
	fi
#######################################################################################
	
echo -en "\tEnter an Option:"
read -n 1 option
}


while [ 1 ]
do
	menu
	case $option in
	0)
	break ;;
	1)
	status ;;

	2)
	lastconnect ;;

	3)
	smart ;;

	4)
	disconnect ;;

	5)
	pref ;;

	6)
	nlockon ;;

	7)
	las ;;

	8)
	vernum ;;

	!)
	nlockoff ;;

	$)
	enteract ;;

	a)
	dallas ;;

	b)
	la ;;

	c)
	la2 ;;

	d)
	ny ;;

	e)
	sanfran ;;

	f)
	seattle ;;

	g)
	dc ;;

	h)
	amsterdam ;;

	i)
	belgium ;;

	j)
	elondon ;;

	k)
	frankfurt ;;

	l)
	hkong2 ;;

	m)
	milan ;;

	n)
	paris1 ;;

	o)
	switzerland2 ;;

	p)
	toronto ;;


	*)
	clear
	echo ""
	echo ""
	echo ""	
	echo "                        Invalid Selection";;
	esac
#	echo -en "\n\n\t\t\tHit any key to continue"
#       read -n 1 line
done
clear



